// frontend/src/components/Units/UnitList.vue
<template>
  <div class="unit-management">
    <div class="header">
      <h1>Unit Management</h1>
      <button class="btn-primary" @click="showCreateModal = true">+ Add New Unit</button>
    </div>

    <div v-if="error" class="alert alert-error">{{ error }}</div>

    <!-- Search and Filters -->
    <div class="filters-section">
      <div class="search-box">
        <input
          v-model="searchTerm"
          type="text"
          placeholder="Search by unit number or block..."
          class="search-input"
          @input="handleSearch"
        />
      </div>

      <div class="filter-group">
        <select v-model="statusFilter" @change="handleFilterChange" class="filter-select">
          <option value="">All Status</option>
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
          <option value="Vacant">Vacant</option>
          <option value="Disputed">Disputed</option>
        </select>

        <select v-model="unitTypeFilter" @change="handleFilterChange" class="filter-select">
          <option value="">All Types</option>
          <option v-for="type in unitTypes" :key="type" :value="type">{{ type }}</option>
        </select>

        <select v-model="blockFilter" @change="handleFilterChange" class="filter-select">
          <option value="">All Blocks</option>
          <option v-for="block in blocks" :key="block" :value="block">{{ block }}</option>
        </select>
      </div>
    </div>

    <!-- Units Table -->
    <div class="units-table-container">
      <div v-if="loading" class="loading">Loading units...</div>

      <div v-else-if="units.length > 0">
        <table class="units-table">
          <thead>
            <tr>
              <th>Unit Number</th>
              <th>Block</th>
              <th>Floor</th>
              <th>Area (sqft)</th>
              <th>Type</th>
              <th>Status</th>
              <th>Member</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="unit in units" :key="unit.id">
              <td class="unit-number">{{ unit.unit_number }}</td>
              <td>{{ unit.block }}</td>
              <td>{{ unit.floor }}</td>
              <td>{{ parseFloat(unit.area_sqft).toFixed(2) }}</td>
              <td>{{ unit.unit_type }}</td>
              <td>
                <span :class="['status-badge', `status-${unit.status.toLowerCase()}`]">
                  {{ unit.status }}
                </span>
              </td>
              <td>
                <span v-if="unit.primary_member" class="member-name">
                  {{ unit.primary_member.owner_name }}
                </span>
                <span v-else class="no-member">No member</span>
              </td>
              <td>
                <div class="action-buttons">
                  <button class="btn-small btn-view" @click="viewUnit(unit.id)">View</button>
                  <button class="btn-small btn-edit" @click="editUnit(unit.id)">Edit</button>
                  <button class="btn-small btn-delete" @click="deleteUnit(unit.id)">Delete</button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>

        <!-- Pagination -->
        <div class="pagination">
          <button 
            :disabled="page === 1"
            @click="previousPage"
            class="btn-pagination"
          >
            Previous
          </button>
          
          <span class="pagination-info">
            Page {{ page }} of {{ totalPages }} (Total: {{ totalCount }} units)
          </span>
          
          <button 
            :disabled="page === totalPages"
            @click="nextPage"
            class="btn-pagination"
          >
            Next
          </button>
        </div>
      </div>

      <div v-else class="no-results">No units found</div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import axios from 'axios';

const API_BASE_URL = process.env.VUE_APP_API_URL || 'http://localhost:8000/api';

// State
const units = ref([]);
const loading = ref(false);
const error = ref(null);
const page = ref(1);
const pageSize = 20;
const totalCount = ref(0);

// Filters
const searchTerm = ref('');
const statusFilter = ref('');
const unitTypeFilter = ref('');
const blockFilter = ref('');
const blocks = ref([]);
const unitTypes = ref([]);
const showCreateModal = ref(false);

// Computed
const totalPages = computed(() => Math.ceil(totalCount.value / pageSize));

// Methods
const fetchUnits = async () => {
  loading.value = true;
  error.value = null;
  
  try {
    const params = new URLSearchParams();
    params.append('page', page.value);
    params.append('limit', pageSize);
    if (searchTerm.value) params.append('search', searchTerm.value);
    if (statusFilter.value) params.append('status', statusFilter.value);
    if (unitTypeFilter.value) params.append('unit_type', unitTypeFilter.value);
    if (blockFilter.value) params.append('block', blockFilter.value);
    
    const response = await axios.get(`${API_BASE_URL}/units/`, {
      params,
      headers: { 'Authorization': `Bearer ${localStorage.getItem('access_token')}` }
    });
    
    units.value = response.data.results;
    totalCount.value = response.data.count;
  } catch (err) {
    error.value = err.response?.data?.detail || 'Failed to fetch units';
    console.error('Error fetching units:', err);
  } finally {
    loading.value = false;
  }
};

const fetchFilters = async () => {
  try {
    const response = await axios.get(`${API_BASE_URL}/units/`, {
      params: { limit: 1000 },
      headers: { 'Authorization': `Bearer ${localStorage.getItem('access_token')}` }
    });
    
    blocks.value = [...new Set(response.data.results.map(u => u.block))];
    unitTypes.value = [...new Set(response.data.results.map(u => u.unit_type))];
  } catch (err) {
    console.error('Error fetching filters:', err);
  }
};

const handleSearch = () => {
  page.value = 1;
  fetchUnits();
};

const handleFilterChange = () => {
  page.value = 1;
  fetchUnits();
};

const previousPage = () => {
  if (page.value > 1) {
    page.value--;
    fetchUnits();
  }
};

const nextPage = () => {
  if (page.value < totalPages.value) {
    page.value++;
    fetchUnits();
  }
};

const viewUnit = (unitId) => {
  console.log('View unit:', unitId);
};

const editUnit = (unitId) => {
  console.log('Edit unit:', unitId);
};

const deleteUnit = (unitId) => {
  if (confirm('Are you sure you want to delete this unit?')) {
    console.log('Delete unit:', unitId);
  }
};

// Lifecycle
onMounted(() => {
  fetchUnits();
  fetchFilters();
});
</script>

<style scoped>
@import './UnitManagement.css';
</style>

// frontend/src/components/Units/UnitList.jsx
import React, { useState, useEffect, useCallback, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import api, { deleteUnit, bulkImportUnits } from '../../services/api';
import { AuthContext } from '../../contexts/AuthContext';
import './UnitManagement.css';

/**
 * Unit List Component
 * Displays a list of units with search, filter, and pagination
 */
const UnitList = () => {
  const [units, setUnits] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [page, setPage] = useState(1);
  const pageSize = 20;
  const [totalCount, setTotalCount] = useState(0);
  const navigate = useNavigate();
  
  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [unitTypeFilter, setUnitTypeFilter] = useState('All');
  const [blockFilter, setBlockFilter] = useState('All');
  
  // Unit data for filters
  const [blocks, setBlocks] = useState([]);
  const [unitTypes, setUnitTypes] = useState([]);

  // Fetch units
  const fetchUnits = useCallback(async () => {
    setLoading(true);
    setError(null);
    
    try {
      const params = {
        page,
        limit: pageSize,
      };

      if (searchTerm) params.search = searchTerm;
      if (statusFilter !== 'All') params.status = statusFilter;
      if (unitTypeFilter !== 'All') params.unit_type = unitTypeFilter;
      if (blockFilter !== 'All') params.block = blockFilter;
      
      const response = await api.get('units/', { params });
      setUnits(response.data.results || []);
      setTotalCount(response.data.count || 0);
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to fetch units');
      console.error('Error fetching units:', err);
    } finally {
      setLoading(false);
    }
  }, [page, pageSize, searchTerm, statusFilter, unitTypeFilter, blockFilter]);

  // Fetch available filters
  const fetchFilters = useCallback(async () => {
    try {
      const response = await api.get('units/', { params: { limit: 1000 } });
      
      // Extract unique blocks and unit types
      const uniqueBlocks = [...new Set((response.data.results || []).map(u => u.block))];
      const uniqueTypes = [...new Set((response.data.results || []).map(u => u.unit_type))];
      
      setBlocks(uniqueBlocks);
      setUnitTypes(uniqueTypes);
    } catch (err) {
      console.error('Error fetching filters:', err);
    }
  }, []);

  useEffect(() => {
    fetchUnits();
  }, [fetchUnits]);

  useEffect(() => {
    fetchFilters();
  }, [fetchFilters]);

  const handleDeleteUnit = async (unitId) => {
    if (!window.confirm('Delete this unit?')) return;

    try {
      await deleteUnit(unitId);
      setUnits((prev) => prev.filter((unit) => unit.id !== unitId));
      setTotalCount((prev) => Math.max(0, prev - 1));
    } catch (err) {
      console.error('Could not delete unit', err);
      alert('Unable to delete unit. Please try again.');
    }
  };

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
    setPage(1);
  };

  const handleStatusChange = (e) => {
    setStatusFilter(e.target.value);
    setPage(1);
  };

  const handleUnitTypeChange = (e) => {
    setUnitTypeFilter(e.target.value);
    setPage(1);
  };

  const handleBlockChange = (e) => {
    setBlockFilter(e.target.value);
    setPage(1);
  };

  const totalPages = Math.ceil(totalCount / pageSize);

  const handleBulkImport = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    try {
      setLoading(true);
      const response = await bulkImportUnits(formData);
      
      alert(`Bulk import completed!\nCreated: ${response.data.success}\nUpdated: ${response.data.updated ?? 0}\nFailed: ${response.data.failed}`);
      fetchUnits();
    } catch (err) {
      alert(`Bulk import failed: ${err.response?.data?.error || err.message}`);
    } finally {
      setLoading(false);
      e.target.value = '';
    }
  };

  const { role } = useContext(AuthContext);
  const canCreateUnit = role === 'Admin';
  const canModifyUnit = role === 'Admin';
  const unitPermissionNote = 'Only Admin can create, edit, delete, or import units.';

  const handleDownloadTemplate = () => {
    const header = 'unit_number,block,floor,area_sqft,unit_type,status,occupancy_status,invoice_frequency';
    const sample = 'A-101,A,1,850.00,Residential,Active,Owner Occupied,Monthly';
    const csv = [header, sample].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'units_import_template.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="unit-management">
      <div className="header">
        <h1>Unit Management</h1>
        <div className="header-actions">
          <button
            className="btn-primary"
            onClick={() => navigate('/units/new')}
            disabled={!canCreateUnit}
            title={!canCreateUnit ? unitPermissionNote : ''}
          >
            + Add New Unit
          </button>
          <button
            className="btn-secondary"
            onClick={handleDownloadTemplate}
            title="Download CSV template with all supported columns"
          >
            Download Template
          </button>
          <label
            className="btn-secondary"
            title={!canCreateUnit ? unitPermissionNote : ''}
            aria-disabled={!canCreateUnit}
          >
            Import CSV
            <input
              type="file"
              accept=".csv"
              onChange={handleBulkImport}
              style={{ display: 'none' }}
              disabled={!canCreateUnit}
            />
          </label>
        </div>
      </div>
      <p className="permission-legend">Disabled actions depend on your role permissions.</p>

      {error && <div className="alert alert-error">{error}</div>}

      {/* Search and Filters */}
      <div className="filters-section">
        <div className="search-box">
          <input
            type="text"
            placeholder="Search by unit number or block..."
            value={searchTerm}
            onChange={handleSearch}
            className="search-input"
          />
        </div>

        <div className="filter-group">
          <select value={statusFilter} onChange={handleStatusChange} className="filter-select">
            <option value="All">All Status</option>
            <option value="Active">Active</option>
            <option value="Inactive">Inactive</option>
            <option value="Vacant">Vacant</option>
            <option value="Disputed">Disputed</option>
          </select>

          <select value={unitTypeFilter} onChange={handleUnitTypeChange} className="filter-select">
            <option value="All">All Types</option>
            {unitTypes.map(type => (
              <option key={type} value={type}>{type}</option>
            ))}
          </select>

          <select value={blockFilter} onChange={handleBlockChange} className="filter-select">
            <option value="All">All Blocks</option>
            {blocks.map(block => (
              <option key={block} value={block}>{block}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Units Table */}
      <div className="units-table-container">
        {loading && <div className="loading">Loading units...</div>}
        
        {!loading && units.length > 0 && (
          <>
            <table className="units-table">
              <thead>
                <tr>
                  <th>Unit Number</th>
                  <th>Block</th>
                  <th>Floor</th>
                  <th>Area (sqft)</th>
                  <th>Type</th>
                  <th>Occupancy</th>
                  <th>Invoice Freq.</th>
                  <th>Status</th>
                  <th>Member</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {units.map(unit => (
                  <tr key={unit.id}>
                    <td className="unit-number">{unit.unit_number}</td>
                    <td>{unit.block}</td>
                    <td>{unit.floor}</td>
                    <td>{parseFloat(unit.area_sqft).toFixed(2)}</td>
                    <td>{unit.unit_type}</td>
                    <td>{unit.occupancy_status || 'Owner Occupied'}</td>
                    <td>{unit.invoice_frequency || '—'}</td>
                    <td>
                      <span className={`status-badge status-${unit.status.toLowerCase()}`}>
                        {unit.status}
                      </span>
                    </td>
                    <td>
                      {unit.primary_member ? (
                        <span className="member-name">{unit.primary_member.owner_name}</span>
                      ) : (
                        <span className="no-member">No member</span>
                      )}
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button className="btn-small btn-view" onClick={() => navigate(`/units/${unit.id}`)}>View</button>
                        <button
                          className="btn-small btn-edit"
                          onClick={() => navigate(`/units/${unit.id}/edit`)}
                          disabled={!canModifyUnit}
                          title={!canModifyUnit ? unitPermissionNote : ''}
                        >
                          Edit
                        </button>
                        <button
                          className="btn-small btn-delete"
                          onClick={() => handleDeleteUnit(unit.id)}
                          disabled={!canModifyUnit}
                          title={!canModifyUnit ? unitPermissionNote : ''}
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Pagination */}
            <div className="pagination">
              <button 
                onClick={() => setPage(Math.max(1, page - 1))}
                disabled={page === 1}
                className="btn-pagination"
              >
                Previous
              </button>
              
              <span className="pagination-info">
                Page {page} of {totalPages} (Total: {totalCount} units)
              </span>
              
              <button 
                onClick={() => setPage(Math.min(totalPages, page + 1))}
                disabled={page === totalPages}
                className="btn-pagination"
              >
                Next
              </button>
            </div>
          </>
        )}

        {!loading && units.length === 0 && (
          <div className="no-results">No units found</div>
        )}
      </div>
    </div>
  );
};

export default UnitList;
