// frontend/src/components/Members/MemberList.vue
<template>
  <div class="member-management">
    <div class="header">
      <h1>Member Management</h1>
      <div class="header-actions">
        <button class="btn-primary" @click="showCreateModal = true">+ Add New Member</button>
        <label class="btn-secondary">
          Import CSV
          <input 
            type="file" 
            accept=".csv" 
            @change="handleBulkImport"
            style="display: none"
          />
        </label>
      </div>
    </div>

    <div v-if="error" class="alert alert-error">{{ error }}</div>

    <!-- Search and Filters -->
    <div class="filters-section">
      <div class="search-box">
        <input
          v-model="searchTerm"
          type="text"
          placeholder="Search by name, email, phone, or unit..."
          class="search-input"
          @input="handleSearch"
        />
      </div>

      <div class="filter-group">
        <select v-model="membershipStatus" @change="handleFilterChange" class="filter-select">
          <option value="">All Status</option>
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
          <option value="Suspended">Suspended</option>
          <option value="Left">Left</option>
        </select>

        <select v-model="occupantType" @change="handleFilterChange" class="filter-select">
          <option value="">All Types</option>
          <option value="Owner">Owner</option>
          <option value="Tenant">Tenant</option>
          <option value="Caretaker">Caretaker</option>
          <option value="Co-owner">Co-owner</option>
        </select>

        <select v-model="paymentPref" @change="handleFilterChange" class="filter-select">
          <option value="">All Payment Preferences</option>
          <option value="Online">Online Transfer</option>
          <option value="Check">Check</option>
          <option value="Cash">Cash</option>
          <option value="Auto-Debit">Auto-Debit</option>
        </select>
      </div>
    </div>

    <!-- Members Table -->
    <div class="members-table-container">
      <div v-if="loading" class="loading">Loading members...</div>

      <div v-else-if="members.length > 0">
        <table class="members-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Unit</th>
              <th>Type</th>
              <th>Phone</th>
              <th>Email</th>
              <th>Status</th>
              <th>Payment Preference</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="member in members" :key="member.id">
              <td class="member-name">{{ member.owner_name }}</td>
              <td class="unit-number">{{ member.unit_number }}</td>
              <td>{{ member.occupant_type }}</td>
              <td>{{ member.contact_phone }}</td>
              <td>{{ member.contact_email }}</td>
              <td>
                <span :class="['status-badge', `status-${member.membership_status.toLowerCase()}`]">
                  {{ member.membership_status }}
                </span>
              </td>
              <td>{{ member.payment_preference }}</td>
              <td>
                <div class="action-buttons">
                  <button class="btn-small btn-view" @click="viewMember(member.id)">View</button>
                  <button class="btn-small btn-edit" @click="editMember(member.id)">Edit</button>
                  <button class="btn-small btn-delete" @click="deleteMember(member.id)">Delete</button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>

        <!-- Pagination -->
        <div class="pagination">
          <button 
            :disabled="page === 1"
            @click="previousPage"
            class="btn-pagination"
          >
            Previous
          </button>
          
          <span class="pagination-info">
            Page {{ page }} of {{ totalPages }} (Total: {{ totalCount }} members)
          </span>
          
          <button 
            :disabled="page === totalPages"
            @click="nextPage"
            class="btn-pagination"
          >
            Next
          </button>
        </div>
      </div>

      <div v-else class="no-results">No members found</div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import axios from 'axios';

const API_BASE_URL = process.env.VUE_APP_API_URL || 'http://localhost:8000/api';

// State
const members = ref([]);
const loading = ref(false);
const error = ref(null);
const page = ref(1);
const pageSize = 20;
const totalCount = ref(0);

// Filters
const searchTerm = ref('');
const membershipStatus = ref('');
const occupantType = ref('');
const paymentPref = ref('');
const showCreateModal = ref(false);

// Computed
const totalPages = computed(() => Math.ceil(totalCount.value / pageSize));

// Methods
const fetchMembers = async () => {
  loading.value = true;
  error.value = null;
  
  try {
    const params = new URLSearchParams();
    params.append('page', page.value);
    params.append('limit', pageSize);
    if (searchTerm.value) params.append('search', searchTerm.value);
    if (membershipStatus.value) params.append('membership_status', membershipStatus.value);
    if (occupantType.value) params.append('occupant_type', occupantType.value);
    if (paymentPref.value) params.append('payment_preference', paymentPref.value);
    
    const response = await axios.get(`${API_BASE_URL}/members/`, {
      params,
      headers: { 'Authorization': `Bearer ${localStorage.getItem('access_token')}` }
    });
    
    members.value = response.data.results;
    totalCount.value = response.data.count;
  } catch (err) {
    error.value = err.response?.data?.detail || 'Failed to fetch members';
    console.error('Error fetching members:', err);
  } finally {
    loading.value = false;
  }
};

const handleSearch = () => {
  page.value = 1;
  fetchMembers();
};

const handleFilterChange = () => {
  page.value = 1;
  fetchMembers();
};

const previousPage = () => {
  if (page.value > 1) {
    page.value--;
    fetchMembers();
  }
};

const nextPage = () => {
  if (page.value < totalPages.value) {
    page.value++;
    fetchMembers();
  }
};

const handleBulkImport = async (e) => {
  const file = e.target.files?.[0];
  if (!file) return;

  const formData = new FormData();
  formData.append('file', file);

  try {
    loading.value = true;
    const response = await axios.post(`${API_BASE_URL}/members/bulk-import/`, formData, {
      headers: { 
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
        'Content-Type': 'multipart/form-data'
      }
    });
    
    alert(`Bulk import completed!\nSuccess: ${response.data.success}\nFailed: ${response.data.failed}`);
    fetchMembers();
  } catch (err) {
    alert(`Bulk import failed: ${err.response?.data?.error || err.message}`);
  } finally {
    loading.value = false;
    e.target.value = '';
  }
};

const viewMember = (memberId) => {
  console.log('View member:', memberId);
};

const editMember = (memberId) => {
  console.log('Edit member:', memberId);
};

const deleteMember = (memberId) => {
  if (confirm('Are you sure you want to delete this member?')) {
    console.log('Delete member:', memberId);
  }
};

// Lifecycle
onMounted(() => {
  fetchMembers();
});
</script>

<style scoped>
@import './MemberList.css';
</style>

// frontend/src/components/Members/MemberList.jsx
import React, { useState, useEffect, useCallback, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import api, { deleteMember } from '../../services/api';
import { AuthContext } from '../../contexts/AuthContext';
import './MemberList.css';

/**
 * Member List Component
 * Displays a list of members with search, filter, and pagination
 */
const MemberList = () => {
  const [members, setMembers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [page, setPage] = useState(1);
  const pageSize = 20;
  const [totalCount, setTotalCount] = useState(0);
  const navigate = useNavigate();
  
  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [membershipStatus, setMembershipStatus] = useState('All');
  const [occupantType, setOccupantType] = useState('All');
  const [paymentPref, setPaymentPref] = useState('All');

  // Fetch members
  const fetchMembers = useCallback(async () => {
    setLoading(true);
    setError(null);
    
    try {
      const params = {
        page,
        limit: pageSize,
      };

      if (searchTerm) params.search = searchTerm;
      if (membershipStatus !== 'All') params.membership_status = membershipStatus;
      if (occupantType !== 'All') params.occupant_type = occupantType;
      if (paymentPref !== 'All') params.payment_preference = paymentPref;
      
      const response = await api.get('members/', { params });
      setMembers(response.data.results || []);
      setTotalCount(response.data.count || 0);
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to fetch members');
      console.error('Error fetching members:', err);
    } finally {
      setLoading(false);
    }
  }, [page, pageSize, searchTerm, membershipStatus, occupantType, paymentPref]);

  useEffect(() => {
    fetchMembers();
  }, [fetchMembers]);

  const handleDeleteMember = async (memberId) => {
    if (!window.confirm('Delete this member?')) return;

    try {
      await deleteMember(memberId);
      setMembers((prev) => prev.filter((member) => member.id !== memberId));
      setTotalCount((prev) => Math.max(0, prev - 1));
    } catch (err) {
      console.error('Unable to delete member', err);
      alert('Unable to delete member. Please try again.');
    }
  };

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
    setPage(1);
  };

  const handleStatusChange = (e) => {
    setMembershipStatus(e.target.value);
    setPage(1);
  };

  const handleOccupantTypeChange = (e) => {
    setOccupantType(e.target.value);
    setPage(1);
  };

  const handlePaymentPrefChange = (e) => {
    setPaymentPref(e.target.value);
    setPage(1);
  };

  const totalPages = Math.ceil(totalCount / pageSize);
  const invalidMembersCount = members.filter((member) => member.has_contact_validation_errors).length;

  const handleBulkImport = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('file', file);

    try {
      setLoading(true);
      const response = await api.post('members/bulk-import/', formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });
      
      alert(`Bulk import completed!\nSuccess: ${response.data.success}\nFailed: ${response.data.failed}`);
      fetchMembers();
    } catch (err) {
      alert(`Bulk import failed: ${err.response?.data?.error || err.message}`);
    } finally {
      setLoading(false);
      e.target.value = '';
    }
  };

  const { role } = useContext(AuthContext);
  const canCreateMember = ['Admin', 'Treasurer', 'Board Member'].includes(role);
  const canModifyMember = ['Admin', 'Treasurer', 'Board Member'].includes(role);
  const canImportMembers = role === 'Admin';
  const memberPermissionNote = 'Only Admin, Treasurer, or Board Member can create, edit, or delete members.';
  const importPermissionNote = 'Only Admin can import members.';

  return (
    <div className="member-management">
      <div className="header">
        <h1>Member Management</h1>
        <div className="header-actions">
          <button
            className="btn-primary"
            onClick={() => navigate('/members/new')}
            disabled={!canCreateMember}
            title={!canCreateMember ? memberPermissionNote : ''}
          >
            + Add New Member
          </button>
          <label
            className="btn-secondary"
            title={!canImportMembers ? importPermissionNote : ''}
            aria-disabled={!canImportMembers}
          >
            Import CSV
            <input
              type="file"
              accept=".csv"
              onChange={handleBulkImport}
              style={{ display: 'none' }}
              disabled={!canImportMembers}
            />
          </label>
        </div>
      </div>
      <p className="permission-legend">Disabled actions depend on your role permissions.</p>

      {error && <div className="alert alert-error">{error}</div>}
      {!error && invalidMembersCount > 0 && (
        <div className="alert alert-warning">
          {invalidMembersCount} member(s) on this page have invalid contact details. They are highlighted in the list.
        </div>
      )}

      {/* Search and Filters */}
      <div className="filters-section">
        <div className="search-box">
          <input
            type="text"
            placeholder="Search by name, email, phone, or unit..."
            value={searchTerm}
            onChange={handleSearch}
            className="search-input"
          />
        </div>

        <div className="filter-group">
          <select value={membershipStatus} onChange={handleStatusChange} className="filter-select">
            <option value="All">All Status</option>
            <option value="Active">Active</option>
            <option value="Inactive">Inactive</option>
            <option value="Suspended">Suspended</option>
            <option value="Left">Left</option>
          </select>

          <select value={occupantType} onChange={handleOccupantTypeChange} className="filter-select">
            <option value="All">All Types</option>
            <option value="Owner">Owner</option>
            <option value="Tenant">Tenant</option>
            <option value="Caretaker">Caretaker</option>
            <option value="Co-owner">Co-owner</option>
          </select>

          <select value={paymentPref} onChange={handlePaymentPrefChange} className="filter-select">
            <option value="All">All Payment Preferences</option>
            <option value="Online">Online Transfer</option>
            <option value="Check">Check</option>
            <option value="Cash">Cash</option>
            <option value="Auto-Debit">Auto-Debit</option>
          </select>
        </div>
      </div>

      {/* Members Table */}
      <div className="members-table-container">
        {loading && <div className="loading">Loading members...</div>}
        
        {!loading && members.length > 0 && (
          <>
            <table className="members-table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Unit</th>
                  <th>Type</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Status</th>
                  <th>Payment Preference</th>
                  <th>Validation</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {members.map(member => (
                  <tr
                    key={member.id}
                    className={member.has_contact_validation_errors ? 'member-row-invalid' : ''}
                  >
                    <td className="member-name">{member.owner_name}</td>
                    <td className="unit-number">{member.unit_number}</td>
                    <td>{member.occupant_type}</td>
                    <td>{member.contact_phone}</td>
                    <td>{member.contact_email}</td>
                    <td>
                      <span className={`status-badge status-${member.membership_status.toLowerCase()}`}>
                        {member.membership_status}
                      </span>
                    </td>
                    <td>{member.payment_preference}</td>
                    <td>
                      {member.has_contact_validation_errors ? (
                        <div className="validation-errors-cell">
                          {(member.contact_validation_errors || []).map((item, index) => (
                            <div key={index} className="validation-error-item">{item}</div>
                          ))}
                        </div>
                      ) : (
                        <span className="validation-ok">Valid</span>
                      )}
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button className="btn-small btn-view" onClick={() => navigate(`/members/${member.id}`)}>View</button>
                        <button
                          className="btn-small btn-edit"
                          onClick={() => navigate(`/members/${member.id}/edit`)}
                          disabled={!canModifyMember}
                          title={!canModifyMember ? memberPermissionNote : ''}
                        >
                          Edit
                        </button>
                        <button
                          className="btn-small btn-delete"
                          onClick={() => handleDeleteMember(member.id)}
                          disabled={!canModifyMember}
                          title={!canModifyMember ? memberPermissionNote : ''}
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Pagination */}
            <div className="pagination">
              <button 
                onClick={() => setPage(Math.max(1, page - 1))}
                disabled={page === 1}
                className="btn-pagination"
              >
                Previous
              </button>
              
              <span className="pagination-info">
                Page {page} of {totalPages} (Total: {totalCount} members)
              </span>
              
              <button 
                onClick={() => setPage(Math.min(totalPages, page + 1))}
                disabled={page === totalPages}
                className="btn-pagination"
              >
                Next
              </button>
            </div>
          </>
        )}

        {!loading && members.length === 0 && (
          <div className="no-results">No members found</div>
        )}
      </div>
    </div>
  );
};

export default MemberList;
